### ISSUE TITLE
Issues serving webjars content

### ISSUE THREAD

**Issue by dvddhln** [microprofile-extensions/openapi-ext#1]
Hi,
I tried using the extension but have issues serving the webjars content? This is what came out of the network. I am not running the project as a webapp but just as a pure jax rs rest service.

![screenshot from 2018-10-31 16-52-18](https://user-images.githubusercontent.com/2706002/47800934-73bf8c00-dd2d-11e8-90c8-bffc0836cbe4.png)

Kind Regards,

David

**Comment by phillip-kruger** [comment]
Hi David.
Yes, webjars work only if it's a webapp (servlet). See https://www.webjars.org/documentation#servlet3

You should be able to just include the javascrip libraries and your own index.html file yourself, but then this library does not add a lot of value.

**Comment by dvddhln** [comment]
I understand, thanks alot Philip! This can be closed.

**Comment by phillip-kruger** [comment]
closing
