### ISSUE TITLE
Openapi-ext getting an error with ApplicationPath = "/" using payara micro

### ISSUE THREAD

**Issue by lePauloRicardo** [microprofile-extensions/openapi-ext#10]
Hi regarding the issue #7, using payara micro, it was still not working, so I cloned the repository and by replacing  `@Path("{path: ^webjars\\/.*}")` with `@Path("{path: webjars/.*}")` it worked. 
Can we use this path? Can it be updated, or won't it work on other implementations?

_(edit: typo)_

**Comment by phillip-kruger** [comment]
You can do a PR, also look at the example and make sure it works there using Thorntail.

**Comment by lePauloRicardo** [comment]
Hi All
this was also affecting open liberty.
The fix worked with the three sample implementations.

**Comment by phillip-kruger** [comment]
Thanks for the fix !
