### ISSUE TITLE
Properties with dashes cannot be passed through environment variables

### ISSUE THREAD

**Issue by kret11** [microprofile-extensions/openapi-ext#3]
I tried to set `openapi-ui.yamlUrl` property with env variable, but it is impossible to use dashes in bash variables. Am I wrong? Is there are chance for changing properties not to use dashes?

**Comment by phillip-kruger** [comment]
Hi ! Thanks for logging the issue. Yes this would be an issue. It's only tested with including this in META-INF/microprofile-config.properties. I'll make a change soon to fix this.
Thanks

**Comment by kret11** [comment]
sent you pull request

**Comment by phillip-kruger** [comment]
Awesome ! Looking at it now !

**Comment by kret11** [comment]
one more PR, with README update
