### ISSUE TITLE
Unable to invoke WhiteLabel.init() version 1.1.4 (works fine in version 1.1.3)

### ISSUE THREAD

**Issue by luisdanielmesa** [microprofile-extensions/openapi-ext#34]
I switched to version 1.1.4 from version 1.1.3 and I get this error:

`WELD-000049: Unable to invoke public void org.microprofileext.openapi.swaggerui.Templates.afterCreate() on org.microprofileext.openapi.swaggerui.Templates@bf217f5 ->null ->WELD-000049: Unable to invoke public void org.microprofileext.openapi.swaggerui.WhiteLabel.init() on org.microprofileext.openapi.swaggerui.WhiteLabel@660e1f3 ->null ->java.io.InputStream.readAllBytes()[B`

It seems like it's trying to read a logo, and the inputstream fails. It works if I switch back to version 1.1.3

If you need help with debugging I might be able to help. **I'm using JDK 1.8_251.** Do I need to use a JVM >= 9?

The method `readAllBytes` doesn't exist before Java 9: https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html

**Comment by phillip-kruger** [comment]
Yes, from 1.1.4 you need JDK > 8

**Comment by luisdanielmesa** [comment]
Thank you for the quick response! Have a good day.
