### ISSUE TITLE
swagger-ui module name is unlikely

### ISSUE THREAD

**Issue by rmannibucau** [microprofile-extensions/openapi-ext#6]
Hi,

It can be good to switch the module name to something more unique and avoid to conflict with the real swagger-ui for bundlings which drop the version and groupid.

Romain

**Comment by phillip-kruger** [comment]
Good point. If we move it to Smallrye we will do that. Thanks

**Comment by phillip-kruger** [comment]
Move to smallrye is taking longer than expected. This is now fixed in v 1.1.0
